name: GitHub OAuth Proxy

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  oauth:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Handle OAuth Request
      run: |
        echo "Handling OAuth Request"
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
